/** Fixed Electron IPC channel names; no generic dispatch channel is exposed. */
export const channels = {
  bootstrap: 'dsh-desktop/bootstrap',
  hostPort: 'dsh-desktop/host-port',
  hostFailure: 'dsh-desktop/host-failure',
  intent: 'dsh-desktop/intent',
  intentReady: 'dsh-desktop/intent-ready',
  newTask: 'dsh-desktop/new-task',
  notify: 'dsh-desktop/notify',
  pluginApply: 'dsh-desktop/plugin-apply',
  pluginCancel: 'dsh-desktop/plugin-cancel',
  pluginList: 'dsh-desktop/plugin-list',
  pluginStage: 'dsh-desktop/plugin-stage',
  preferencesGet: 'dsh-desktop/preferences-get',
  preferencesSet: 'dsh-desktop/preferences-set',
  reportSelection: 'dsh-desktop/report-selection',
  restartHost: 'dsh-desktop/restart-host',
  updateGet: 'dsh-desktop/update-get',
  updateCheck: 'dsh-desktop/update-check',
  updateDownload: 'dsh-desktop/update-download',
  updateInstall: 'dsh-desktop/update-install',
  updateCancel: 'dsh-desktop/update-cancel',
  updateOpenReleases: 'dsh-desktop/update-open-releases',
  updateState: 'dsh-desktop/update-state',
} as const
