#ifndef DSH_VPN_LWIPOPTS_H
#define DSH_VPN_LWIPOPTS_H

#define NO_SYS 1
#define SYS_LIGHTWEIGHT_PROT 0
#define LWIP_TIMERS 1
#define LWIP_SOCKET 0
#define LWIP_NETCONN 0
#define LWIP_RAW 0
#define LWIP_CALLBACK_API 1
#define LWIP_IPV4 1
#define LWIP_IPV6 0
#define LWIP_ARP 0
#define LWIP_ETHERNET 0
#define LWIP_DHCP 0
#define LWIP_AUTOIP 0
#define LWIP_IGMP 0
#define IP_FORWARD 0
#define IP_REASSEMBLY 1
#define IP_FRAG 1
#define IP_REASS_MAX_PBUFS 48
#define LWIP_ICMP 1
#define LWIP_UDP 1
#define LWIP_TCP 1
#define LWIP_DNS 1
#define LWIP_DNS_SUPPORT_MDNS_QUERIES 0
#define DNS_MAX_SERVERS 4
#define DNS_TABLE_SIZE 32
#define DNS_MAX_REQUESTS 32
#define DNS_MAX_NAME_LENGTH 255
#define DNS_DOES_NAME_CHECK 1
#define LWIP_DNS_SECURE 7

/* Fixed native resource ceilings; the wrapper admits at most 32 streams. */
#define MEM_ALIGNMENT 8
#define MEM_SIZE (4 * 1024 * 1024)
#define MEM_LIBC_MALLOC 0
#define MEMP_MEM_MALLOC 0
#define MEMP_NUM_TCP_PCB 32
#define MEMP_NUM_TCP_PCB_LISTEN 0
#define MEMP_NUM_UDP_PCB 32
#define MEMP_NUM_TCP_SEG 4096
#define MEMP_NUM_PBUF 1024
#define PBUF_POOL_SIZE 512
#define PBUF_POOL_BUFSIZE 1536
#define TCP_MSS 1460
#define TCP_WND 65535
#define TCP_SND_BUF 65535
#define TCP_SND_QUEUELEN 180
#define TCP_QUEUE_OOSEQ 1
#define TCP_OOSEQ_MAX_BYTES 65535
#define TCP_OOSEQ_MAX_PBUFS 48
#define LWIP_WND_SCALE 0
#define LWIP_TCP_KEEPALIVE 1

#define LWIP_NETIF_HOSTNAME 0
#define LWIP_NETIF_STATUS_CALLBACK 0
#define LWIP_NETIF_LINK_CALLBACK 0
#define LWIP_NETIF_LOOPBACK 0
#define LWIP_HAVE_LOOPIF 0
#define LWIP_STATS 0
#define LWIP_DEBUG 0
#define LWIP_COMPAT_SOCKETS 0
#define LWIP_PROVIDE_ERRNO 0

#endif
